name       : iverilog
version    : 10.3
release    : 2
source     :
    - https://github.com/steveicarus/iverilog/archive/v10_3.tar.gz : 4b884261645a73b37467242d6ae69264fdde2e7c4c15b245d902531efaaeb234
license    : LGPL-2.1
component  : office.scientific
summary    : a Verilog simulation and synthesis tool
description: |
    Icarus Verilog is a Verilog simulation and synthesis tool. It operates as a compiler, compiling source code written in Verilog (IEEE-1364) into some target format. For batch simulation, the compiler can generate an intermediate form called vvp assembly. This intermediate form is executed by the ``vvp'' command. For synthesis, the compiler generates netlists in the desired format.
builddeps  :
    - gperf
patterns   :
    - /usr/include
    - /usr/lib64
setup      : |
    chmod +x autoconf.sh
    ./autoconf.sh
    %configure
build      : |
    %make
install    : |
    %make_install -j1
check      : |
    %make check
